production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: 25

default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: rankingems_development

test:
  <<: *default
  database: rankingems_test
